language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install .
    - pip install -r requirements.txt
    # Deal with issue on Travis builders re: multiprocessing.Queue :(
    - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests, e.g. python setup.py test
script:  py.test
