language: python
python:
  - "3.4"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - 'python setup.py develop'
    # Deal with issue on Travis builders re: multiprocessing.Queue :(
    - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests, e.g. python setup.py test
script:  JIP_LOGLEVEL=DEBUG JIP_DB_LOGLEVEL=DEBUG py.test
